### ISSUE TITLE
Automatic re-run of failed scenarios is shown in a different launch name

### ISSUE THREAD

**Issue by neo81-83** [reportportal/agent-java-cucumber4#25]
Hello Team,

I am using Cucumber 4.7, TestNG along with Java for automation. We have successfully integrated to report portal and are able to see execution status in real time, but the problem/turn off is the failed scenarios when they rerun they are shown under another launch name/number. Is there a workaround or fix available?

Refer to the screenshot below, launch# 127 is my original run where 2 scenarios ran, 1 passes 1 failed. The failed scenario got run under launch# 128 and not '#127'.

![image](https://user-images.githubusercontent.com/56172687/69894178-40617f00-12ea-11ea-80a2-8e42530558ed.png)

**Comment by evjlobanova** [comment]
@neo81-83 which version of ReportPortal and agents do you use?

**Comment by neo81-83** [comment]
Hello @evjlobanova I am using Report Portal 4.3.0 and agent-java-cucumber4 version 4.0.0. Please let me know if you need any additional information.

**Comment by evjlobanova** [comment]
@neo81-83 hello! we added rerun functionality in the version 5.0, you can find a dev guide that describes this feature [here](https://github.com/reportportal/documentation/blob/master/src/md/src/DevGuides/rerun.md)

Try to explore version 5.0 of ReportPortal (RC6 a stable release candidat for this version and agent 5)/

Feel free to reopen this issue, if you still have a problems

**Comment by DzmitryHumianiuk** [comment]
@neo81-83 you should take RPv5 for it.
and then client and agent for v5.

team started with agent update this week.
coming soon.

**Comment by neo81-83** [comment]
Good to know, thanks for the info.

-W

**Comment by HardNorth** [comment]
Fixed in the latests agent versions.
