### ISSUE TITLE
any plan to publish the lib on maven?

### ISSUE THREAD

**Issue by suciista09** [reportportal/agent-java-cucumber4#3]
Hi

our team are really interested using reportportal.io and we already use io.cucumber version 4. So we need this agent version. We can not find the jar on maven or bintray. So, we just clone your project and build manual. But it means we can miss your update. SO, any plan in the near future to publish it? Thanks

**Comment by filland** [comment]
Hello, you can find the dependency for the cucumber agent here 
https://bintray.com/epam/reportportal/agent-java-cucumber
