### ISSUE TITLE
Could not find artifact io.cucumber:messages:jar:10.0.2

### ISSUE THREAD

**Issue by amar-1314** [reportportal/agent-java-cucumber4#37]
Getting the error `Could not find artifact io.cucumber:messages:jar:10.0.2 in bintray-epam-reportportal (http://dl.bintray.com/epam/reportportal)` while using dependency 5.0.0-BETA-9

I don't see a dependency version io.cucumber:messages 10.0.2 in maven central instead I see 10.0.3

**Comment by HardNorth** [comment]
That's ridiculous, they deleted `10.0.2` version or we wouldn't have had the agent compiled. I'll try to update the version with the next release. But now please use exclusions.

**Comment by HardNorth** [comment]
Already fixed
