### ISSUE TITLE
Launch does not finish if cucumber (java) test step is 'pending'

### ISSUE THREAD

**Issue by ManfredGro** [reportportal/agent-java-cucumber4#39]
I'm using reportportal 4.3.0
My test run with cucumber/java 4.7.4 and connect to the portal with agent-java-cucumber4 v4.1.0

In my stepdefinition I throw a PendingException which just means that the step is not yet implemented and is understood by most plugins that work with cucumber.

In reportportal I can see, that all the data regarding the test was recieved (see screenshot). No problem so far.
However reportportal seems to interpret the "pending" as "still running". So the launch never finishes, even so all the test are done and all the data is recieved.
Is there a way to work around this?
![ReportPortal_pending](https://user-images.githubusercontent.com/57143974/67778400-6d104580-fa63-11e9-90c3-60a62b5ad9e7.jpg)

**Comment by gor-p-asx** [comment]
Hi Team - just wondering if this is going to prioritize ? 
Or any fix coming to new version

**Comment by HardNorth** [comment]
@gor-p-asx @minhdoan159 Can anyone of you guys provide a simple little project which reproduces the issue? It would speed-up a fix.

**Comment by gor-p-asx** [comment]
i will try to get sample project but its simple when any step has 
   `     throw new PendingException();`
you should able to see this behaviour

**Comment by HardNorth** [comment]
Abandoned
