### ISSUE TITLE
Getting error when add rp.skipped.issue=FALSE for iosDriver test

### ISSUE THREAD

**Issue by suciista09** [reportportal/agent-java-cucumber4#4]
error details :
- add rp.skipped.issue=FALSE and run test

Error: Unable to launch WebDriverAgent because of xcodebuild failure: "xcodebuild failed with code 65".

but if I change the flag to true or just remove that properties, it run successfully. Additional information, this problem doesn't appear on androidDriver

**Comment by filland** [comment]
@suciista09 hello, do you still face this problem ?
