### ISSUE TITLE
reportportal working jars for cucumber 4.7.1 version?

### ISSUE THREAD

**Issue by code255255** [reportportal/agent-java-cucumber4#46]
,can someone please share working reportportal jar versions for cucumber 4.7.1

**Comment by HardNorth** [comment]
@code255255 What's wrong with these?: https://bintray.com/epam/reportportal/agent-java-cucumber4

**Comment by HardNorth** [comment]
I see you found them: https://github.com/reportportal/reportportal/issues/967
