### ISSUE TITLE
two tests are generated when executing one cucumber scenario under the launch

### ISSUE THREAD

**Issue by code255255** [reportportal/agent-java-cucumber4#47]
I'm using below jar versions
agent-java-testng - 5.0.0-BETA-9
agent-java-cucumber4- 5.0.0-BETA-9
 client-java - 5.0.0-BETA-9
logger-java-logback- 5.0.0-BETA-9
  
Reportportal version - 5.1.0
Cucumber-java - 4.7.1
![Screen Shot 2020-05-13 at 10 05 34 PM](https://user-images.githubusercontent.com/65089586/81888589-47faa480-9567-11ea-9bab-e9c8f4522555.png)

Can you please check.

**Comment by HardNorth** [comment]
What I see here is that you report TestNG launch with a TestNG agent and Cucumber launch with a cucumber agent. Just use only one of them and it will solve your problem.
