### ISSUE TITLE
Not able to load test cases that are executed using Cucumber in REPORTPORTAL

### ISSUE THREAD

**Issue by TestMyCode12345** [reportportal/agent-java-cucumber4#48]
Hi Team,

  I have created one project using cucumber. I am able to run the restNg.xml and all test cases got executed based on feature file within.

Reportportal is up and running. I successfully load test cases that are executed using below link in reportportal

https://github.com/reportportal/example-java-TestNG

But I am not able to launch test cases done in cucumber prject.

Steps followed:

1. pom.xml - added cucumber dependency. (attached screenshot)
2. testing.xml - Added listener.
3. TestRunner.java - Added ScenarioReporter.

4. Reportportal.properties. 

![image](https://user-images.githubusercontent.com/65267827/82530274-95c06f80-9b5a-11ea-83bf-7dc29a5a7963.png)

![image](https://user-images.githubusercontent.com/65267827/82530213-74f81a00-9b5a-11ea-9f4e-997e92cd09a2.png)

![image](https://user-images.githubusercontent.com/65267827/82530166-5560f180-9b5a-11ea-815f-5cff86713730.png)

![image](https://user-images.githubusercontent.com/65267827/82530406-de782880-9b5a-11ea-8edf-d8ecde5153ea.png)

Could you please advice me.

I am new to cucumber.

**Comment by TestMyCode12345** [comment]
Any reason to transfer this issue from reportportal???

**Comment by HardNorth** [comment]
@TestMyCode12345 Because the issue is related to the agent only.
