### ISSUE TITLE
Increased CPU utilisation when running tests in parallel with agent enabled

### ISSUE THREAD

**Issue by albadam000** [reportportal/agent-java-cucumber4#49]
Issue
Multiple tests that are run in 3 threads (in parallel) so it creates 3 launches. Significant increase in utilization is seen on the machine running the tests when report portal is enabled vs disabled

Agent: agent-java-cucumber4 version 4.1.0
![image](https://user-images.githubusercontent.com/13465337/83471169-57667100-a4c7-11ea-8ca3-0531166c2862.png)

**Comment by evjlobanova** [comment]
@Iryna_Kozak2 Ira, please look at this issue and ask needed question please

**Comment by irynakozak2** [comment]
@albadam000 could you please specify the following things:
Which version of ReportPortal do you use?
Your instance configuration(CPU’s number, RAM size)?
Is DB located on the same instance with API?  

Please be informed that ReportPortal has 10 services, which runs together and consume something part of the instance resources, such as CPU, RAM, Disk I/o, network, etc.
  
As I understand your issue, you just up the ReportPortal services(docker-compose or Kubernetes), faced that CPU utilization has been increased, then just stop the ReportPortal and faced lower CPU utilization?  

Could you please correct me if I missed anything?

**Comment by albadam000** [comment]
Hi @irynakozak2 ,
thanks for getting back to me on this. We're running ReportPortal 5.1.0 on Azure Kubernetes; the DB is a SaaS by Azure as well.

The CPU utilization issue is happening on the instance where we are running the test, not where RP is hosted. When agent-java-cucumber4 is enabled in the test configuration, we can see the extreme CPU utilization. When we are running the tests with reporting to RP disabled, the CPU utilization is fine.

Our assumption is that the issue is when agent-java-cucumber4 is combined with parallel test execution, and maybe the launch merging is causing the high cpu problem.

**Comment by irynakozak2** [comment]
@albadam000 thanks a lot for your reply. Could you please try to use the latest version of the cucumber agent (agent-java-cucumber/5.0.0-BETA-11)? Now you use 4 agent version with the ReportPortal v5, I think it's should reduce the issue.

**Comment by HardNorth** [comment]
Abandoned
