### ISSUE TITLE
Launch never finishes but CI job finishes successfully [v5]

### ISSUE THREAD

**Issue by SerhiiKachan** [reportportal/agent-java-cucumber4#54]
We have upgraded RP from 4.3 to 5.2.
Upgraded agents accordingly: 
**agent-java-cucumber4** 5.0.0-Beta-9
**client-java** 5.0.0
**logger-java-logback** 5.0.0

Launch stucks and never finishes until performing force finish manually, however job completes successfully.

![image](https://user-images.githubusercontent.com/33296989/84308289-e9751600-ab66-11ea-9387-10f126ce9a11.png)

Explanation: on the screenshot RP indicates that launch is still running and started 1 hour ago, but it's been already finished within 23 minutes since started.

Previously we hadn't had issue like that in 4th version.

**Comment by HardNorth** [comment]
@SerhiiKachan Can you try the latest version of the agent: 5.0.0-BETA-12?

**Comment by HardNorth** [comment]
Looks abandoned.
