### ISSUE TITLE
[v5]Deep Merge not working properly with ScenarioReporter

### ISSUE THREAD

**Issue by klebercsilva** [reportportal/agent-java-cucumber4#68]
I am running the following stack: Java, TestNG, Cucumber 4.8, Appium. When using the plugin com.epam.reportportal.cucumber.**StepReporter** and performing a **Deep Merge**, Report Portal was doing fine in combining both executions and keeping the most up-to-date tests after the merge operation. Now using com.epam.reportportal.cucumber.**ScenarioReporter** Deep Merge actually seems to be doing a **Linear Merge**.

**Comment by HardNorth** [comment]
It needs to be re-checked.

**Comment by HardNorth** [comment]
Doesn't look like a case anymore, at least for RP version >= 5.3.0 at which I tested it.
