### ISSUE TITLE
Error message is displayed twice for failed step

### ISSUE THREAD

**Issue by alukash** [reportportal/agent-java-cucumber4#71]
Error message is displayed twice for failed step. See the screenshot.
maven-failsafe-plugin is used to run tests.

I think the issue is in AbstractReporter.reportResult method. It sends error message twice:
```
	protected void reportResult(Result result, String message) {
		String level = mapLevel(result.getStatus());
		if (message != null) {
			sendLog(message, level);
		}
		String errorMessage = result.getErrorMessage();
		if (errorMessage != null) {
			sendLog(errorMessage, level);
		}
		if (result.getError() != null) {
			sendLog(getStackTraceAsString(result.getError()), level);
		}
	}
```
**Versions:**
- Report Portal: https://rp.epam.com
- agent-java-cucumber4: 5.0.0
- cucumber-java: 4.8.1

**Attachments**:
![doubleError](https://user-images.githubusercontent.com/5165256/97292443-4d6d5200-185c-11eb-914b-3fca8163e180.png)

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-java-cucumber4/releases/tag/5.0.1
