### ISSUE TITLE
CHILD_START_TIME_EARLIER_THAN_PARENT Exception on cucumber step execution

### ISSUE THREAD

**Issue by SerhiiKachan** [reportportal/agent-java-cucumber4#73]
RP launches start but no test reported to some launches.
Looks like child elements of a launch are not initializing in correct order.
Reproduces randomly on different launches.
Example:
![image](https://user-images.githubusercontent.com/33296989/99245588-7d30c980-280c-11eb-983d-a93b018fe3eb.png)
![image](https://user-images.githubusercontent.com/33296989/99245620-8c177c00-280c-11eb-9ffe-1c59592576e7.png)

It is getting interrupted definetely because of the exception:
[error_log.txt](https://github.com/reportportal/agent-java-cucumber4/files/5546038/error_log.txt)

RP agents used:
client-java : 5.0.11
agent-java-cucumber4 : 5.0.0-RC-1

**Comment by HardNorth** [comment]
Fixed: https://github.com/reportportal/agent-java-cucumber4/releases/tag/5.0.1
