### ISSUE TITLE
java.lang.IllegalStateException: Attempting re-set scenario ID for unfinished scenario

### ISSUE THREAD

**Issue by asamsonov** [reportportal/agent-java-cucumber4#8]
**Setup:**

@CucumberOptions(glue = "stepdef",
        plugin = {
                "pretty", "com.epam.reportportal.cucumber.ScenarioReporter",
       },
        features = "src/test/resources/features/test.feature")

public class RunCukesTest extends AbstractTestNGCucumberTests {

    @Override
    @DataProvider(parallel = true)
    public Object[][] scenarios() {
        return super.scenarios();
    }
}
  
**Description:** 

Parallel execution of cucumber scenarios fails with "java.lang.IllegalStateException: Attempting re-set scenario ID for unfinished scenario"
If you remove com.epam.reportportal.cucumber.ScenarioReporter from @CucumberOptions parallel execution works well. Most likely RP Reporter reuses same id for every example of scenario outline when running in parallel.

**Comment by HardNorth** [comment]
Should be addressed in: #22
