### ISSUE TITLE
Need to get the launch id when saving it in the report portal

### ISSUE THREAD

**Issue by badrinrs** [reportportal/agent-java-cucumber4#83]
This is with respect to https://github.com/reportportal/client-java/issues/180.

I understand that the issue has been addressed in client-java. Can this be addressed in agent-java-cucumber4 as well. This would help in posting test videos and screenshots post test runs. 

Also for updating test status in case of custom frameworks.

**Comment by badrinrs** [comment]
Please release the next version of agent-java-cucumber4 soon as I am waiting for the Launch UUID change. I understand the change has been made in the master branch.

**Comment by HardNorth** [comment]
For those who need an example: [LaunchIdLogging.java](https://github.com/reportportal/examples-java/blob/66904feb655e6df7b83d18d99c89f06ee4094553/example-cucumber6/src/test/java/com/epam/reportportal/example/cucumber6/logging/LaunchIdLogging.java)
