### ISSUE TITLE
Need to create attributes on feature file

### ISSUE THREAD

**Issue by Kamala-PriyankaCog** [reportportal/agent-java-cucumber4#85]
**Describe the bug**
Trying to provide different Severity level for each test case
using- java-agent-cucmber4- version-4.1.1

**Steps to Reproduce**
1. ...added rp.attributes= Severity:low;Medium;high
2. Provided tag as @Medium upon scenario outline
3. Could you please help us on how to add these value sto feture file since it is not described in the official documentation

**Expected behavior**
Should be able to show tets cases count on dashbard by differentiating with different Severity levels
**Actual behavior**
What actually happened.
Not able to filer with Attribute tage
**Dependency versions**
Include version info of the following libraries: client-java, agent-java-cucumber4

**Additional context**

**Comment by HardNorth** [comment]
We already have example which shows tag setting: https://github.com/reportportal/examples-java/blob/master/example-cucumber4/src/test/resources/features/attribute/belly.feature

I modified it to demonstrate feature-level with `@high-severity` tag.
That's how my feature looks after it:
![Screen Shot 2022-07-08 at 1 01 18 PM](https://user-images.githubusercontent.com/4364466/177968528-48baf84f-b715-494c-9269-8c8736851261.png)

If you still not able to set tags please consider agent update, version `4.1.1` is a way too old.
